<?php

namespace AppBundle\Repository;
/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{

    public function getQuestionByThemeId($id){
        return $this->createQueryBuilder('q')
            ->where('q.theme = :theme_id')
            ->setParameter('theme_id', $id)
            ->getQuery()
            ->getResult()
        ;
    }

}
